auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: localhost

schema_config:
  configs:
    - from: 2021-01-01
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
ring:
    kvstore:
      store: inmemory

storage_config:
  boltdb:
    directory: /loki/index

  filesystem:
    directory: /loki/chunks

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
