scrape_configs:
  - job_name: "swarm-service"
    scrape_interval: 10s
    dns_sd_configs:
      - names:
          - "tasks.ministack_minitwit-image"
        type: "A"
        port: 5000
    metrics_path: "/metrics"
