version: '3.3'

networks:
  main:

services:
  minitwit-image:
    image: ${DOCKER_USERNAME}/minitwit-image:latest
    environment:
      - PSQL_CON_STR=${PSQL_CON_STR}
    container_name: minitwit-image

    # Exposing port from container to host
    ports:
        - '80:5000'
        - '5000:5000'

  prmetheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml
      - ../prom_data:/prometheus
    user: '0:0'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

    ports:
      - '9090:9090'
