version: '3.3'

networks:
  main:

services:
  minitwit-image:
    image: ${DOCKER_USERNAME}/minitwit-image:latest
    # image: minitwit-image
    environment:
      - PSQL_CON_STR=${PSQL_CON_STR}
    container_name: minitwit-image

    # Exposing port from container to host
    ports:
        - '80:5000'
        - '5000:5000'

  prmetheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ../config/prometheus.yml:/etc/prometheus/prometheus.yml:z
      - ../prom_data:/prometheus:z
    user: '0:0'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "8080:3000"
    volumes:
      - ../grafana_data/:/var/lib/grafana:z
      - ../config:/etc/grafana/provisioning/datasources:z
    user: '0:0'
