name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  static-code-analysis:
    name: "Run CI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: 1.20.x

      - run: "go test ./..."
      - run: "go vet ./..."
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.3"

          # This uses the above setup go version
          install-go: false
