---
name: Continuous Deployment

on:
  push:
    # Run workflow every time something is pushed to the main branch
    branches:
      - main
      - fix/dev

  # allow manual triggers for now too
  workflow_dispatch:
    manual: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push minitwit-image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwit-imagee:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwit-image:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwit-image:webbuildcache,mode=max

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/do_ssh_key
          chmod 600 ~/.ssh/do_ssh_key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Sync scripts file
        run: >
          scp -i ~/.ssh/do_ssh_key
          -o StrictHostKeyChecking=no
          -r ./scripts root@138.68.126.8:/minitwit/scripts
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      # - name: Deploy to server
      #   # Configure the ~./bash_profile and deploy.sh file on the Vagrantfile
      #   run: >
      #     ssh root@138.68.126.8
      #     -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no
      #     '/minitwit/scripts/deploy.sh'
