name: Integration CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Setup python dependancies
        run: |
          pip install requests
          pip install selenium
          pip install pymongo
          pip install pytest
      - name: start the database
        run: |
          docker run --name my_postgres_db -e POSTGRES_PASSWORD=mysecretpassword -d -p 5431:5432 postgres

      - name: build and run minitwit
        run: |
          docker build -t minitwit-image .
          docker run --network host -d -p 5000:5000 --env PSQL_CON_STR=postgresql://postgres:mysecretpassword@localhost:5431/postgres minitwit-image

      - name: Run refactored tests
        run: python3 ./tests/refactored_minitwit_tests.py
      - name: Run simulator tests
        run: python3 ./tests/minitwit_sim_api_test.py
    # - name: Run UI tests
    #   run: python3 test_itu_minitwit_ui.py
