name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  integration:
    name: "Integration Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Setup python dependancies
        run: |
          pip install requests
          pip install pytest

      - name: start the database
        run: |
          docker run --name my_postgres_db -e POSTGRES_PASSWORD=mysecretpassword -d -p 5431:5432 postgres

      - name: build and run minitwit
        run: |
          docker build -t minitwit-image .
          docker run --network host -d -p 5000:5000 --env PSQL_CON_STR=postgresql://postgres:mysecretpassword@localhost:5431/postgres minitwit-image

      - name: Run refactored tests
        run: python3 ./tests/refactored_minitwit_tests.py
      - name: Run simulator tests
        run: python3 ./tests/minitwit_sim_api_test.py

      # Run e2e when every other integration is done
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"

      - name: Install dependencies
        working-directory: ./client
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./client
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./client
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 30
